service: password-less-app
provider:
  name: aws
  runtime: python3.8
  memorySize: 128
  timeout: 3
  stage: ${self:custom.currentStage}
  logRetentionInDays: 30
  environment:
    LOG_ENABLED: "False"
  logs:
    httpApi: True
  httpApi:
    payload: "2.0"
    cors: True
    authorizers:
      serviceAuthorizer:
        identitySource: $request.header.Authorization
        issuerUrl:
          Fn::Join:
            - ""
            - - "https://cognito-idp."
              - "${opt:region, self:provider.region}"
              - ".amazonaws.com/"
              - Ref: CognitoUserPoolPasswordLessPool
        audience:
          - Ref: CognitoUserPoolClientPasswordLessClient

package:
  individually: True
  include:
    - functions/otp/base.py
  exclude:
    - functions/otp/test/

custom:
  defaultStage: dev
  currentStage: ${opt:stage, self:custom.defaultStage}
  userPoolName: ${self:service}-user-pool-${self:custom.currentStage}
  userPoolClientName: ${self:service}-user-pool-client-${self:custom.currentStage}

functions:
  - ${file(./functions/otp.yml)}
  - ${file(./functions/private.yml)}
resources:
  - ${file(./resources/cognito-user-pool.yml)}
  - ${file(./resources/cognito-user-pool-client.yml)}
  - ${file(./resources/role-notification-sender.yml)}
  - ${file(./resources/role-monitoring-logs.yml)}
  - ${file(./resources/role-cognito-consumer.yml)}
